### ISSUE TITLE
Locations of dead stones persist in review

### ISSUE THREAD

**Issue by mark5000** [online-go/online-go.com#186] opened 2017-03-28 17:43 UTC
### Summary

Upon opening a review, the locations of stones marked "dead" at scoring may be marked with blue squares that will persist through all branches and variations in the review. This happened in game https://online-go.com/game/8170131 , where two reviews ( https://online-go.com/review/234653 and https://online-go.com/review/234648 ) displayed blue squares contrary to one's expectation that the review would open a clean board.

### Environment

 Unknown. Presumably all devices and browsers.

### Steps To Reproduce:

1. Go to a game, such as the one linked, where stones were captured but not removed from the board.
2. Open a review.
3. See that there are blue squares marking the locations of dead stones instead of a clean review board. 

### Additional Information:

![damebug](https://cloud.githubusercontent.com/assets/13010650/24418790/03fb38e8-13a2-11e7-8652-b0d8e27fb1a8.png)

**Comment by anoek** [comment] 2017-03-29 14:58
Duplicate of #67

**Closed by anoek** 2017-03-29 14:58 UTC
