### ISSUE TITLE
Indicate beginning of overtime with an audible cue other than Countdown.

### ISSUE THREAD

**Issue by lemurek** [online-go/online-go.com#7] opened 2017-02-25 14:29 UTC
### Summary

Countdown at the end of base time is unnecessary, as there is nothing real penalty for breaching the threshold there. I.e. if you slip by 1 second, you just lose one second, vs. slip in byo = 1 byo period gone. 

Sometimes I find myself playing a rushed move in the end of base time for no reason other than the misleading extra countdown.

### Environment

 * Operating system: any
 * Browser: any
 * Browser Version: any

### Steps To Reproduce:

1. Start a blitz game under byo-yomi or canadian time control
2. Observe the countdown close to the end of base time

### Additional Information:

Suggested fix:
For base-time only time controls all the cues should be present. For an overtime based time settings (byo-yomi and canadian) the cues should happen only close to the end of overtime period(s).

**Comment by anoek** [comment] 2017-02-27 13:53
I think instead of just disabling this we want to expand on the optionality around voice count down. IE, folks should be able to turn this on or off, change how much of a countdown there is and when, if they want three beeps for the last three seconds or full voice, that sort of thing

**Comment by anoek** [comment] 2017-02-27 17:38
I'm going to close this for now, I'd like any changes to how the clocks behave to be discussed in a more public setting, such as the forums or something of the sort. Once there's been some discussion and input from a number of people and it's clear that the community agrees that X should be done about clocks, then we can open up an issue and alter code.

**Comment by lemurek** [comment] 2017-02-27 18:44
So let me explain my way of thinking here. Normally the countdown is a clear signal that you need to hurry, and indeed in other time settings the urgency is welcome.

In all 3 of:
Base time, Simple and Fischer settings you lose a game, so the move is definietly urgent. 

On the opposite when there is an overtime available, making the move at this point in time is actually disadvantegous. 

In Canadian setup is better to wait 1 extra second in result you gain some time as you need to make only 24 moves instead of 25.
In Byo-Yomi it would be actually best to spend whole extra minute on thinking about the move, which is effectively lost if you make the decision, just before the base time is over.

So that's why I was arguing that this countdown doesn't bring value to players. 

It is indeed related to https://github.com/online-go/online-go.com/issues/5. Instead of a countdown there should be a clear hint that the player is entering the overtime at this point, which somehow relates to the concern I raised in the other issue. 

Of course the decision is yours, but I do think that there are valid, objective reasons to remove the countdown after base time limit.

**Comment by lemurek** [comment] 2017-02-27 18:55
Closing the PR is understandable, as it was simply removing the Countdown without providing other cues in return, however I'd like to keep the issue open. Perhaps as 'replace countdown before overtime with other audible indication of overtime start'

**Comment by roy7** [comment] 2017-02-27 18:59
A hard count at end of main time before entering first free period I agree is overkill, since it's just free time as soon as you submit the move. Perhaps a little chime or bell sound at the end of main time just so you're aware?

**Comment by benjaminpjones** [comment] 2020-10-29 05:30
Was this issue resolved in the [March update](https://forums.online-go.com/t/audio-updates/25208)?

**Comment by BHydden** [comment] 2020-10-29 05:36
Yes, there are a variety of notification and countdown sound options [here](https://www.youtube.com/watch?v=O3TsVaFR870).

**Comment by benjaminpjones** [comment] 2020-10-29 06:28
Just wondering if there is anything outstanding, since the issue is open

**Comment by anoek** [comment] 2020-10-30 11:40
Thanks for bringing that up! Good to finally close old issues.

**Closed by anoek** 2020-10-30 11:40 UTC
Labels: feature request
