### ISSUE TITLE
Nice to have feature: automatic counting of marked spots

### ISSUE THREAD

**Issue by gezabohus** [online-go/online-go.com#1638] opened 2022-01-16 11:36 UTC
When analyzing a one can use triangle, square etc marks. It would be nice if the system automatically displayed a count for these on the board making it easier to do score estimates manually. For instance, given the situation in the attached file, the UI would display the face that there are 10 triangles.
<img width="643" alt="Screen Shot 2022-01-16 at 12 35 21" src="https://user-images.githubusercontent.com/10329508/149658253-850ee39d-9101-430e-9e20-26ba45664dc9.png">

**Comment by benjaminpjones** [comment] 2022-01-16 18:32
>the UI would display the face that there are 10 triangles.

Just to try to nail down some details on this request, where in the UI would this be displayed?  On the board? On the side?  To be determined?

**Comment by BHydden** [comment] 2022-01-16 18:34
Why don't you just use the number tool?

![image](https://user-images.githubusercontent.com/28991649/149673164-08e8095d-a018-416e-a8fc-5c23a716b78d.png)

**Comment by benjaminpjones** [comment] 2022-01-16 19:45
I knew this looked familiar.. Closing as duplicate of #1363

**Closed by benjaminpjones** 2022-01-16 19:45 UTC
