### ISSUE TITLE
Last update hides part of game names on mobile

### ISSUE THREAD

**Issue by ISibboI** [online-go/online-go.com#1207] opened 2020-07-20 13:33 UTC
Hi, the update that went live looks like this for me:
![Screenshot_20200720-163033](https://user-images.githubusercontent.com/2361822/87943387-a3389e00-caa6-11ea-9824-8025d71bc58c.png)

While I can scroll to the right to see the columns on the right, it is impossible to scroll to the left to see the titles of the games.

**Comment by benjaminpjones** [comment] 2021-02-23 22:43
@ISibboI is this on Chrome? I wasn't able to reproduce, but I also couldn't find commits that would have fixed this...

![Screenshot_20210223-174127_Chrome](https://user-images.githubusercontent.com/25233703/108917965-95c83100-75fe-11eb-98c0-c85a57a2a5ef.jpg)

**Comment by benjaminpjones** [comment] 2021-02-23 23:14
Whoops I was looking at GameList.styl, not Overview.styl.

Looks like @flovo fixed this in #1210! Moving to close.

**Closed** 2022-01-04 12:48 UTC
