### ISSUE TITLE
Player's online statuses do not update when waking computer from sleep.

### ISSUE THREAD

**Issue by Nazgand** [online-go/online-go.com#315] opened 2017-05-31 22:02 UTC
After waking my laptop, I noticed that my opponent still showed as online in the game, even though they were offline on the friends list. The game had already ended, but I doubt that makes a difference. This probably also happens when waking the computer from hibernation.

**Comment by BarneyStratford** [comment] 2017-09-06 18:43
Duplicate of #263.

**Closed** 2019-05-26 17:59 UTC
Labels: bug
