### ISSUE TITLE
Site doesn't load when localStorage is disabled

### ISSUE THREAD

**Issue by pelevesque** [online-go/online-go.com#28] opened 2017-02-26 07:43 UTC
### Summary

The site used to work in safari on my iphone 5s. It no longer does. After loading, it just shows a completely white page.

---
 anoek: This is caused by the fact that safari in private mode doesn't allow the use of localStorage.

### Environment

 * Hardware: iphone 5s 
 * Operating system: iOS 10.1.1 (14B100)
 * Browser: Safari
 * Browser Version: Not sure. The one with iOS 10.1.1

### Steps To Reproduce:

1. Load site (with localStorage disabled, eg with safari in private browsing mode)
2. You'll get a blank page.

**Comment by anoek** [comment] 2017-02-26 12:06
Can you take some screenshots of any errors you see on the debug console? I've never tried this, but perhaps these instructions will help for getting  to that information: https://www.lifewire.com/activate-the-debug-console-in-safari-445798

**Comment by mark5000** [comment] 2017-02-26 16:21
I could not reproduce the white screen on an iPhone 5s. However, the interface leaves something to be desired. Portrait mode is pretty much unusable.

![img_2076](https://cloud.githubusercontent.com/assets/13010650/23341422/4c9612f2-fbfc-11e6-90b6-a559c827cd86.PNG)

Landscape mode is better, although there's overlap all over the place.

![img_2077](https://cloud.githubusercontent.com/assets/13010650/23341424/4f9d0bfe-fbfc-11e6-96ca-adc7f1e16463.PNG)

**Comment by weej** [comment] 2017-02-26 16:43
My Windows phone 8.1 also looks like this image, with overlapping text.

**Comment by anoek** [comment] 2017-02-26 16:48
Yep, all that is related to https://github.com/online-go/online-go.com/issues/34  - basically we "just" need to make our table widget and the game list widget collapse nicely on mobile (and probably something on the overview page to fix that overlapping issue as well)

**Comment by pelevesque** [comment] 2017-02-27 05:54
I get these 3 errors using web inspector with my iphone 5s.

![screen shot 2017-02-27 at 12 52 44 am](https://cloud.githubusercontent.com/assets/4752429/23350245/455c0c22-fc87-11e6-8ad6-c93648fd0900.png)

**Comment by anoek** [comment] 2017-02-27 12:33
@pelevesque Interesting, that looks like local storage is disabled for some reason. According to http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st safari blocks local storage when in Private Browsing Mode, are you by any chance in private browsing mode?

**Comment by pelevesque** [comment] 2017-02-27 13:37
Yes, I was in private browsing mode. The site works now that I removed it. Thanks.

**Comment by anoek** [comment] 2017-02-27 14:02
Cool, closing this issue then and tracking the mobile layout stuff in https://github.com/online-go/online-go.com/issues/34

**Comment by anoek** [comment] 2017-02-27 14:03
Actually keeping open so we can make a patch to more gracefully handle this situation. (We don't need to hard error.. we won't be able to store any settings, but folks should be able to log in and play just fine in private mode)

**Comment by blamarche** [comment] 2017-02-27 15:04
What should be an easy bootstrap fix is on the page init set window.localStorage if its undefined to a shell object with the same key functions.

**Closed** 2017-03-02 20:53 UTC
Labels: bug
