### ISSUE TITLE
Activating Firefox "privacy.resistFingerprinting" breaks Board

### ISSUE THREAD

**Issue by phikal** [online-go/online-go.com#1429] opened 2021-03-17 14:04 UTC
**Describe the bug**
When I enable Firefox `privacy.resistFingerprinting` option in `about:config`, stones on all Go board misrender:

**To Reproduce**
1. Open `about:config`
2. Set `privacy.resistFingerprinting` to True
3. Open any OGS board

**Expected behavior**
I would expect the stones to render normally.

**Screenshots**

![image](https://user-images.githubusercontent.com/6370419/111480088-7fa71f80-8729-11eb-87de-52d8f66e08a2.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 33
 - Browser Firefox
 - Version: 86.0 (64-bit)

**Comment by anoek** [comment] 2021-03-17 14:10
Feel free to report that to Firefox, I suspect the issue is that we render our stones to a canvas and then paste those onto the board image. As I understand it, some canvas fingerprinting techniques involves pasting things on canvases and looking at the minor differences between systems. That's something that needs to be fixed by standards, nothing we can do about it.

**Closed by anoek** 2021-03-17 14:10 UTC

**Comment by phikal** [comment] 2021-03-17 14:11
Ok, thank you for the pointer.

**Comment by phikal** [comment] 2021-11-23 21:05
For anyone stumbling upon this thread: It seems that when setting `privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts` to false, this issue can be migitated, without disabling fingerprint resistance.
