### ISSUE TITLE
Hidden bot not hidden.

### ISSUE THREAD

**Issue by Dorus** [online-go/online-go.com#1209] opened 2020-07-25 05:40 UTC
When connecting, bots emit
```Js
socket.emit('bot/hidden', !!config.hidden);
```
to inform OGS if they should be listed in the AI list. Bot that generally do not accept games usually hide them self.

![afbeelding](https://user-images.githubusercontent.com/4461459/88449789-08dfae00-ce4a-11ea-8f5a-f0c68476634b.png)

But recently, even hidden bots show up in this list. For example, my 00b bot.

**Comment by wonderingabout** [comment] 2020-07-25 07:29
i could reproduce this in https://github.com/online-go/gtp2ogs/issues/364

this should not be caused by any gtp2ogs, as this also happens with a branch where i tested --hidden to work

**Comment by egri-nagy** [comment] 2020-08-01 23:02
I can confirm that this is still an issue. I had two bots on the same computer (RPi2), and the one, which was meant to be hidden, went public also. I got more traffic, and both bots went down. Now I cannot really experiment with the settings to get them back online, as I get challenges for the bots.

**Comment by wonderingabout** [comment] 2020-08-02 08:39
@egri-nagy to regulate maximum load on your bots you can use maxconnectedgames (https://github.com/online-go/gtp2ogs/blob/devel/docs/OPTIONS-LIST.md#maxconnectedgames, default is 20 which is most likely to high on your machine r7 1700 16gb ram gtx1060 6 gb, i personally run maxconnectedgames 2 or 3), and optionally also maxconnectedgamesperuser (which i set to 1 personally)

to experiment these settings and run maximum load on all bots stability tests, you can run on beta ogs instead, there you will receive no challenge from any player, or you could start with rejectnew to reject all challenges and only accept your own challenges manually from your bot account until you hit maximum load desired

**Comment by Dorus** [comment] 2020-08-02 09:21
@egri-nagy It might help you to experiment on https://beta.online-go.com/

**Comment by anoek** [comment] 2020-08-04 13:40
This should be fixed now, on both beta and production

**Closed by anoek** 2020-08-04 13:40 UTC
