### ISSUE TITLE
SGF downloads don't always work

### ISSUE THREAD

**Issue by roy7** [online-go/online-go.com#21] opened 2017-02-25 21:54 UTC
Some games you can download SGF files for, and some you cannot. Ones that cannot just give me a network error in Chrome. Someone else told me they were able to download an SGF I was not, although the terminator at the end of the SGF was missing.

https://online-go.com/game/7792296

Is a game I can't download the SGF from, as an example.

Further discussion and more example games that can't download SGF:

https://forums.online-go.com/t/cant-download-sgf-file/10784

**Comment by ck244** [comment] 2017-03-01 18:32
I posted this in the forum as well, but I wonder if the issue is due to unicode handling of the chat. For example, the accented "a" in the username of someone in the chat for the linked game: "HoàngDuyKhang".

Here is my forum comment:
"I've seen this error in the old UI, perhaps now it's due to bad unicode handling in the chat as opposed to usernames, see this thread: https://forums.online-go.com/t/sgf-downloads-broken-for-non-latin-characters-in-usernames/8616/13"

**Comment by roy7** [comment] 2017-03-05 04:07
I'd really love to get these two SGFs downloaded. Putting a comment here so once this is closed I'll have a reminder to go back and get them. :)

https://online-go.com/game/7961745
https://online-go.com/game/7962387

**Comment by anoek** [comment] 2017-03-07 14:17
A fix has been implemented on the backend for at least one of the reasons for the sgf downloading issues, will see if it resolves the second issue as well.

**Comment by roy7** [comment] 2017-03-07 14:36
I'll be happy to test some broken downloads out once the fixes are pushed out to live server. ;)

**Comment by roy7** [comment] 2017-03-08 00:04
I'm not sure if non-latin character names is one of the reason's you've already fixed, but this comment was made on Help channel:

laszlo743: I can't download the sgf file of any game in which one of the players has a user name containing non-latin characters.

**Comment by anoek** [comment] 2017-03-08 00:07
Yep that fix is up on beta, insure if that's all it was with the Leela
games though

**Comment by roy7** [comment] 2017-03-08 00:21
Beta doesn't tie to non-beta game records right though? So I can't actually test broken downloads of main server until it goes live?

**Comment by anoek** [comment] 2017-03-08 00:27
Correct

On Mar 7, 2017 19:21, "Jonathan Roy" <notifications@github.com> wrote:

Beta doesn't tie to non-beta game records right though? So I can't actually
test broken downloads of main server until it goes live?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/online-go/online-go.com/issues/21#issuecomment-284905105>,
or mute the thread

**Comment by anoek** [comment] 2017-03-08 12:44
Fixed

**Closed by anoek** 2017-03-08 12:44 UTC
Labels: bug, needs api support
