### ISSUE TITLE
Capture time usage in SGF

### ISSUE THREAD

**Issue by zakimaksyutov** [online-go/online-go.com#2587] opened 2024-02-18 21:55 UTC
Strategies might be different compared on how much time left (seconds vs. minutes). Blunders also can occur more often while under time pressure. Right now, it is not possible to account for this while reviewing SGF.

Ideal experience is similar to how Lichess (and other chess clients) implemented it. It is possible to export time usage. And while reviewing a game the remaining time is shown.

The only alternative available is to if there is a video recording of an entire game then analyze right away and capture time-caused blunders/decisions right in comments. This is not scalable solution and doesn't apply for games without video recording in the first place.

**Comment by benjaminpjones** [comment] 2024-02-19 01:33
Closing as duplicate of https://github.com/online-go/online-go.com/issues/1204

**Closed by benjaminpjones** 2024-02-19 01:33 UTC
Labels: feature request
