### ISSUE TITLE
Game history should show player's rank at the time of the game.

### ISSUE THREAD

**Issue by lrperlmu** [online-go/online-go.com#542] opened 2017-12-15 03:19 UTC
### Summary

Past games appear with players' present ranks. They should appear with the rank at the time the game was played.

### Environment
N/A

### Steps To Reproduce:

1. View Game History in each player's profile.

### Additional Information:
Link to forum post:
https://forums.online-go.com/t/why-in-past-games-the-username-appears-with-the-present-rank/11921

**Comment by arnaudgo** [comment] 2017-12-15 15:57
Hello !

Looks like a duplicate of #364  :)

Arnaud

**Closed** 2019-05-26 17:55 UTC
Labels: bug
