### ISSUE TITLE
Cannot edit nor delete group news

### ISSUE THREAD

**Issue by juanchodepisa** [online-go/online-go.com#71] opened 2017-03-03 03:25 UTC
### Summary

News posted on group pages cannot be edited or deleted by group admins. That possibility existed before the release of version 5, but this is no longer the case.

This is inconvenient, for there is no way to correct mistakes made in news publications, or clean up old/irrelevant/false information posted in the past.

### Additional Information:

The edit button allows to modify group description and bulletin, but not news.

**Comment by mlopezviedma** [comment] 2017-03-03 03:34
This is a duplicate of #54

**Comment by anoek** [comment] 2017-03-03 11:53
As @mlopezviedma , dup of #54

**Closed by anoek** 2017-03-03 11:53 UTC
