### ISSUE TITLE
Plan Conditional Moves did not work

### ISSUE THREAD

**Issue by David263** [online-go/online-go.com#2182] opened 2023-03-04 22:43 UTC
**Describe the bug**
In game https://online-go.com/game/51553214, which is part of the 9x9 Ladder, I anticipated move D1 in my Plan Conditional Moves section, but my specified response move was not automatically played.

**To Reproduce**
1. Go to the above game
2. Search for the D1 move.
3. Notice that my conditional move had to be played manually.

**Expected behavior**
The move I specified should have been played automatically, giving white another chance to play, then my followup move should have been played automatically too.

**Screenshots**
I don't think a screenshot now would be of help.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Windows Home 64
 - Browser [e.g. chrome, safari]FF 
 - Version [e.g. 22]110.0.1 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I love the conditional moves because with only 3 chances and 3days per chance, it is very rare to be able to get a game when joining the 9x9 Ladder. Conditional moves let me do a little more in the one chance I have every few hours to play in a Ladder game.

**Comment by David263** [comment] 2023-03-07 14:10
Conditional moves seem not to be working in another Ladder game, too. Is this a known problem? It would be very nice to have conditional moves working, since one must frequently wait for hours for the next opponent move.

**Comment by BHydden** [comment] 2023-03-07 18:38
Since nobody else is reporting this, it's entirely possible this is user error.

After putting in your moves, are you clicking the accept conditional moves button?

**Comment by David263** [comment] 2023-03-07 18:42
Yes. Perhaps the problem is that I'm using FF? Sometimes programmers target Chrome rather than FF.

**Comment by GreenAsJade** [comment] 2023-04-12 11:52
I think anoek uses FF    😄

**Comment by anoek** [comment] 2023-04-12 11:59
Yep I develop on firefox and spot check on chrome, Safari is the on that catches me by surprise sometimes these days.

So, spot checking I can't find anything wrong with conditional moves over here, if you can find something reproducible that would be a great help. Until then I'm going to close this as not something we can diagnose to fix, because it seems to be working.

**Closed by anoek** 2023-04-12 11:59 UTC
