### ISSUE TITLE
Active games list view incorrectly displaying opponent

### ISSUE THREAD

**Issue by RobertT53** [online-go/online-go.com#64] opened 2017-03-02 05:23 UTC
### Summary

Active game list view displays whoever is playing black instead of the opponents name.

### Environment

 * Operating system: Windows 10
 * Browser: Any 

### Steps To Reproduce:

1. Go to a users page with enough active games to sort by list.
2. See their name is listed under the "Opponent" column if they are playing black.

### Additional Information:

[Example from forums](https://ogs-forums.s3.amazonaws.com/original/2X/0/0da923b1f094b8713c591ab9f4983c9367904f73.png)

**Comment by BarneyStratford** [comment] 2017-03-04 20:12
I have a counterexample to the claim that it lists only the black players. https://online-go.com/game/7466601 is in the Active Games list at https://online-go.com/player/179886/, with her playing white and her opponent listed as herself. The game is the one at move 205 with no clock. I am her opponent, so I'll arrange that we don't make any more moves.

**Comment by BarneyStratford** [comment] 2017-03-04 23:51
I know why this is happening now. In order to work out who is the player's opponent, data.get ("user") is compared with Black and White's users. The problem is that data.get ("user") is the currently logged-in user, who is a third party to the games. Hence, the calculation of who is the opponent goes awry. Working on a fix.

**Comment by anoek** [comment] 2017-03-07 12:26
Fixed with https://github.com/online-go/online-go.com/pull/102

**Closed** 2017-03-07 12:26 UTC
Labels: bug
