### ISSUE TITLE
Tournament creates 2 games at once. 1 game does not display in the pairings.

### ISSUE THREAD

**Issue by kjruiy** [online-go/online-go.com#2058] opened 2022-10-27 06:59 UTC
**Describe the bug**
I have been in a few live double elimination tournaments which created multiple games at once for 1 round.

**To Reproduce**
One tournament is here.
https://online-go.com/tournament/96112

The two games were here, and I did not receive notification for the first, only the second, then it appears the round was considered a timeout.
https://online-go.com/game/view/48136860
https://online-go.com/game/48136857

My opponent in the  second game was recorded as receiving a bye despite having played that  game.

**Expected behavior**
Tournament expected to pair 1 game per round and notify for that  game.

**Comment by Sofia-mal** [comment] 2022-10-27 13:34
See also https://github.com/online-go/online-go.com/issues/2023

**Comment by Sofia-mal** [comment] 2023-01-14 22:45
https://online-go.com/tournament/98450 Here a rare case of "4 games instead of 1"

**Comment by dexonsmith** [comment] 2024-02-05 03:11
Closing as a duplicate of the slightly-older bug #2023, since it seems to be the same problem.

**Closed** 2024-02-06 07:14 UTC
Labels: bug, duplicate
