### ISSUE TITLE
Ranking shown in game history not matching rank shown elsewhere

### ISSUE THREAD

**Issue by anahata0108** [online-go/online-go.com#1336] opened 2020-12-27 21:16 UTC
**Describe the bug**
When browsing for games, or anywhere else that a player's rank is listed (their profile, chat, etc.), the rank that is displayed does not match the rank shown on the user's profile under "game history". This causes confusion when trying to challenge / accept a challenge. One may seem to be within rank range to do so, but because the actual rank (shown in Game History on the profile page) is outside of this range, one is unable to accept said challenges.

**To Reproduce**
1. View [my profile on OGS](https://online-go.com/player/892762/anahata)
2. Note in the upper left that my rank is shown as 25k.
3. Scroll down to "Game History" and notice that my rank shows 26k for [this game](https://online-go.com/game/29557621) and probably others

**Expected behavior**
The rank shown for a user matches what their game history rank says they are

**Screenshots**
<img width="283" alt="image" src="https://user-images.githubusercontent.com/44044/103179927-b2debe80-485e-11eb-8ddc-ecb44adeedf7.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/44044/103179925-af4b3780-485e-11eb-83db-2ed62f2fabe2.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.1 Big Sur
 - Browser Safari, Chrome, Firefox
 - Version 14.0.2, 87.0.4280.88, 85.0b4 respectively (production releases of Firefox are not yet stable on Apple Silicon Macs)

**Comment by GreenAsJade** [comment] 2021-03-21 00:19
(Just to save potential confusion, this bug report is talking specifically about the top entry in the game history table, which I agree should be the person's current rank)

**Comment by anoek** [comment] 2021-03-21 00:22
It was widely desired from the community that the game history table show the ranks of the players when the game was played, so that's why it's the way it is.

I'm open to other thoughts on how to make that less confusing, but I don't think we're going to be changing that behavior.

**Comment by GreenAsJade** [comment] 2021-03-21 05:44
That's what I was trying to clarify :D

The problem reported here is not (as you first think reading it) that "the historical ranks don't match today's rank".

The problem is that the final rank _should_ match today's rank.

The question that this ticket asks is "how can my rank by 25k now, if it was 26k after the end of my most recent game"?

Note that I have checked, and the rank being shown is definitely the "after the game" rank, not the "when the game started" rank.  So surely the most recent one should match the current rank...

**Comment by anoek** [comment] 2021-03-21 11:52
Oh gotcha,

The bug would be that the rank in the history is showing the rank after the game then, it should be the rank of the players when the game was played (not after the game was played and their ranks were updated)

**Comment by benjaminpjones** [comment] 2021-03-21 13:56
>The problem is that the final rank should match today's rank.

IIUC, the rank in the game history is the rank *immediately before* the rank is updated at the end of the game.  If that is the case, the rank at the profile would not need to match the rank in the most recent game played, and this is WAI.

That said, I empathize with the confusion, as I also had assumed it was the rank *after* the rank is updated until @pdg137 [explained it to me](https://forums.online-go.com/t/how-automatic-handicap-is-calculated/31964/26?u=benjito).

**Comment by pdg137** [comment] 2021-03-22 06:31
Wasn't the original complaint that the rank displayed on this user's profile was not their actual rank?

[Here's a current example](https://online-go.com/player/943081/):

![image](https://user-images.githubusercontent.com/466760/111948603-a6a08100-8a9c-11eb-896e-dcac60c580c5.png)

A rating of 605 is actually supposed to be `30 - ln(605 / 525) * 23.15` which equals 26.7k, but it's displayed as 25.0k.  In the game history you can see a more accurate 27k (though maybe this number is one game out of date).

I think this is related to #1403.

**Comment by benjaminpjones** [comment] 2021-03-22 07:20
>Wasn't the original complaint that the rank displayed on this user's profile was not their actual rank?

The original complaint was that the rank shown at the top of game history does not match the current rank.

While the 25k cap may have played into this at the time of posting, it is no longer a factor if you look at anahata's page:

![Screenshot_20210322-025617_Chrome](https://user-images.githubusercontent.com/25233703/111952672-d9a63d00-8abb-11eb-8705-3b1fb3fb752e.jpg)
![Screenshot_20210322-030328_Chrome](https://user-images.githubusercontent.com/25233703/111952680-ddd25a80-8abb-11eb-9268-e206d36bec11.jpg)

Now the ranks are 16k (current) and 17k (at time of last ranked game).  This user is relatively new, so being one game out of date actually does make a difference in their rank.  I just wanted to point out that there is this off-by-one aspect to the game history, and that the current rank cannot generally be found in the game history, as the OP implies.

**Comment by pdg137** [comment] 2021-03-22 14:44
Right, OP's rank has gone up so the issue probably doesn't affect them anymore. But as originally reported, it's true that a rank of 26k will not be shown in the profile. If there is still supposed to be a "25k cap", but it's not applied everywhere, that's a bug. OP was not just complaining about the game history but _also_ reported that their "actual" rank affects ability to accept challenges, which is believable but harder to test.

**Comment by GreenAsJade** [comment] 2021-03-24 10:17
The 25k think was a good catch, but I don't understand what you mean by "off by one is a feature of game history"

I, and the OP, had mistakenly thought that the rank showing in game history was the rank _after_ that game.

But as benjaminjones points out, it is not the rank after the game, it is the rank before the game.

Therefore this issue should indeed be closed.

**Comment by pdg137** [comment] 2021-03-24 15:40
I don't understand why you would say this was "a good catch" but close the issue.  It's not fixed, right?  Would you prefer a new one that doesn't (confusingly) bring up the game history as evidence for the issue?

**Comment by BHydden** [comment] 2021-03-24 17:00
> I don't understand why you would say this was "a good catch" but close the issue.  

Issue isn't closed..? He closed it 4 days ago but reopened it 3 days ago when the point was clarified.

**Comment by GreenAsJade** [comment] 2021-03-25 09:00
Right - to be really clear: this is working as expected.  The player's rank in the game history is their rank as they entered that game, not their rank after they finished it.

**Comment by BHydden** [comment] 2021-03-25 09:06
And is also intentionally not capped to the 25k lower-bound to reflect their actual rating at the time rather than their pairing.

**Closed** 2022-01-04 12:53 UTC
