### ISSUE TITLE
Pass button showing for wrong player in forked game 

### ISSUE THREAD

**Issue by shinuito** [online-go/online-go.com#2093] opened 2022-12-30 12:11 UTC
I recently forked a game to test the scoring phase, but for some reason the pass button is showing for the wrong player

![8B6F6511-A182-4CCA-9DC2-3938C0A69E93](https://user-images.githubusercontent.com/26803867/210068844-d8108129-0439-41b1-ab05-fa899428ac85.jpeg)
![A16D2EB9-E3F9-4507-BD3A-CB3ECC092A55](https://user-images.githubusercontent.com/26803867/210068846-be181be9-9264-4d57-9279-89339ebbc1b0.jpeg)

It’s this game but it’s private https://online-go.com/game/49756269. It was forked at this point so no moves have been played yet, just the komi adjusted to account for missing captures.

There’s an error that displays when the black player tries to pass, something about it not being your turn, but it disappears very quickly.

**Comment by shinuito** [comment] 2022-12-30 12:19
After a couple of moves however it seemed to have fixed itself however.

**Comment by benjaminpjones** [comment] 2022-12-30 15:01
Duplicate of #2088

**Closed by benjaminpjones** 2022-12-30 15:01 UTC

**Comment by benjaminpjones** [comment] 2022-12-30 15:05
The problem is that the code checks for the last player to move to figure out whether to show pass. If it is the first move of the game, it assumes black to play.  This assumption is faulty in the case of forks and handicap games.
